### ISSUE TITLE
Filtering sensitive params from an event

### ISSUE THREAD

**Issue by ianks** [piotrmurach/tty-logger#4]
### Describe the problem

Currently, tty-logger does not filter out sensitive params from rack. The filtering config will only replace string literals that match, which is not very useful for things like passwords which only have a hash of the string.

### Expected behaviour
`config.filters` will look for keys specified in the `params` of an object to be logged.

Here is how we are patching TTY::Logger to deal with this:

```ruby
module TTY
  class Logger
    module Formatters
      module ParamFiltering
        def dump(obj, *args)
          filter_params!(obj)

          super
        end

        private

        def filter_params!(obj)
          target = obj[:params] || obj['params']

          return unless target

          Logger.config.filters.each do |param_name_to_filter|
            filter_param!(target, param_name_to_filter)
            filter_param!(target, param_name_to_filter.to_sym)
          end
        end

        def filter_param!(target, param_name_to_filter)
          return unless target.key?(param_name_to_filter)

          target[param_name_to_filter] = '[FILTERED]'
        end
      end
    end
  end
end

TTY::Logger::Formatters::Text.prepend(TTY::Logger::Formatters::ParamFiltering)
TTY::Logger::Formatters::JSON.prepend(TTY::Logger::Formatters::ParamFiltering)
```

**Comment by piotrmurach** [comment]
Hi Ian,

Thanks for using `tty-logger` and reporting this.

I'd be very keen to change `filter` implementation to include more complex matching behaviour beyond strings. It would be good to allow more complex objects including checking nested hashes for keys. Extending formatters is probably not the place to do it as these should be only responsible for decorating data.

Do you have any time to submit PR with a sample implementation or failing test case that describes example input?

**Comment by piotrmurach** [comment]
There is a new way to filter messages and data, please see [filters](https://github.com/piotrmurach/tty-logger#242-filters). If you have time to give it a try from the master branch that would be great. I will release a new gem shortly.

**Comment by piotrmurach** [comment]
Released `v0.3.0` with the new filters. Happy New Year!

**Comment by adam12** [comment]
> There is a new way to filter messages and data, please see [filters](https://github.com/piotrmurach/tty-logger#242-filters). If you have time to give it a try from the master branch that would be great. I will release a new gem shortly.

I ran into this too and [did my own implementation](https://github.com/adam12/roda-enhanced_logger/blob/b0d3c1e464265e02ae5b84bd2442d2ef924d76e7/lib/roda/plugins/enhanced_logger.rb#L25-L36). Happy to see it upstream now! Cheers.

**Comment by ianks** [comment]
Awesome stuff. I’ll give it a whirl next week.

**Comment by piotrmurach** [comment]
@ianks please report back as I want to make sure the API works well.

@adam12 Great stuff, thanks for using this gem! 🙏 I'd encourage you to switch over to new API. It filters also hashes nested inside arrays. Plus, you can expose message vs data filtering configuration in your gem.
