### ISSUE TITLE
Document tty-logger-raven

### ISSUE THREAD

**Issue by ianks** [piotrmurach/tty-logger#6]
No problem here, just letting you know I built a gem which integrates tty-logger with Sentry.io. This makes debugging on errors much more joyful!

Check it out here: https://github.com/ianks/tty-logger-raven

Thanks for the great gem 😀

**Comment by piotrmurach** [comment]
Magic! I suggest we add it somewhere in the docs handlers section. Maybe new menu item like `3rd party`? Would you have time to submit PR?
