### ISSUE TITLE
Cannot filter runtime parameters information

### ISSUE THREAD

**Issue by amyspark** [piotrmurach/tty-logger#7]
### Are you in the right place?
* For issues or feature requests file a GitHub issue in this repository
* For general questions or discussion post in [Gitter](https://gitter.im/piotrmurach/tty)

### Describe the problem

Loggers should be configurable at runtime. At present, they are only configurable at initialization; if I use `tty-option`, the parameter information is available only after `parse`.

### Steps to reproduce the problem

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'tty-command'
require 'tty-logger'
require 'tty-option'

# rubocop disable Style/Documentation
class Demo
  include TTY::Option

  argument :arg1 do
    required
  end

  def initialize
    @logger = TTY::Logger.new do |config|
      config.metadata = %i[date time]
      config.filters.data = %i[arg1]
      config.level = :debug
    end
    @cmd = TTY::Command.new(printer: :null)
  end

  def protect_params
    @logger = @logger.copy Hash.new do |config|
      config.filters.message = [params[:arg1]]
    end
  end

  def demo
    @logger.info "running demo"

    @cmd.run "cat /etc/hosts; echo #{params[:arg1]}; false"
  end

  def run!
    parse
    protect_params
    demo
  rescue StandardError => e
    @logger.fatal 'Error:', e
  end
end

Demo.new.run!
```

### Actual behaviour

`@logger.configuration` is inaccessible, thus I need to copy it before adding `arg1`'s value to `config.message`.

### Expected behaviour

I should not need to copy a logger to customize its filtering.

### Describe your environment

* OS version: `5.4.34-1-MANJARO`
* Ruby version: `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]`
* TTY version:  `tty-command (0.9.0)`, `tty-logger (0.3.0)`

**Comment by piotrmurach** [comment]
💯 Agree. I think the configuration should be exposed on the logger instance via `configure` method that accepts a configuration block. Do you have time to work on a PR?
